apiVersion: v1
kind: ConfigMap
metadata:
  name: metanode-public-nginx-config
  namespace: metanode
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        # SDK Download and Documentation
        location /download/ {
            alias /usr/share/nginx/html/;
            autoindex on;
        }
        
        # API Access for SDK clients
        location /api/ {
            proxy_pass http://api-server:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # IPFS Gateway
        location /ipfs/ {
            proxy_pass http://ipfs:8080/ipfs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Faucet for test tokens
        location /faucet/ {
            alias /usr/share/nginx/html/faucet/;
            try_files $uri $uri/ /faucet/index.html;
        }
        
        # Explorer
        location /explorer/ {
            alias /usr/share/nginx/html/explorer/;
            try_files $uri $uri/ /explorer/index.html;
        }
        
        # Root - redirect to download page
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-gateway
  namespace: metanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-gateway
  template:
    metadata:
      labels:
        app: public-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: sdk-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: metanode-public-nginx-config
      - name: sdk-content
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: public-gateway
  namespace: metanode
spec:
  selector:
    app: public-gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: public-gateway-external
  namespace: metanode
spec:
  selector:
    app: public-gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
